# Generated by Django 5.2.5 on 2025-08-15 22:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "privacy_level",
                    models.IntegerField(
                        choices=[
                            (1, "Public"),
                            (2, "Friends only"),
                            (3, "Private"),
                            (4, "Hidden from all"),
                        ],
                        default=3,
                        help_text="Default privacy level for user data",
                    ),
                ),
                (
                    "default_retention_policy",
                    models.CharField(
                        choices=[
                            ("immediate", "Delete immediately"),
                            ("daily", "Delete after 24 hours"),
                            ("weekly", "Delete after 7 days"),
                            ("monthly", "Delete after 30 days"),
                            ("quarterly", "Delete after 90 days"),
                            ("yearly", "Delete after 365 days"),
                            ("never", "Never delete automatically"),
                        ],
                        default="monthly",
                        help_text="Default retention policy for user-generated content",
                        max_length=20,
                    ),
                ),
                (
                    "auto_delete_messages",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically delete messages after retention period",
                    ),
                ),
                (
                    "auto_delete_documents",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically delete documents after retention period",
                    ),
                ),
                (
                    "enable_two_factor",
                    models.BooleanField(
                        default=False, help_text="Enable two-factor authentication"
                    ),
                ),
                (
                    "enable_encryption",
                    models.BooleanField(
                        default=True,
                        help_text="Enable end-to-end encryption for sensitive data",
                    ),
                ),
                (
                    "anonymize_on_delete",
                    models.BooleanField(
                        default=True, help_text="Anonymize data instead of hard delete"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="User biography", max_length=500
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="User avatar image",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "last_data_export",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user exported their data",
                        null=True,
                    ),
                ),
                (
                    "last_data_purge",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user purged their data",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Session timeout in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "max_sessions",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum concurrent sessions allowed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed IP addresses",
                    ),
                ),
                (
                    "blocked_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of blocked IP addresses",
                    ),
                ),
                (
                    "notify_on_login",
                    models.BooleanField(
                        default=True, help_text="Send notification on successful login"
                    ),
                ),
                (
                    "notify_on_failed_login",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification on failed login attempts",
                    ),
                ),
                (
                    "notify_on_data_export",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification when data is exported",
                    ),
                ),
                (
                    "notify_on_data_deletion",
                    models.BooleanField(
                        default=True, help_text="Send notification when data is deleted"
                    ),
                ),
                (
                    "recovery_email",
                    models.EmailField(
                        blank=True, help_text="Recovery email address", max_length=254
                    ),
                ),
                (
                    "recovery_phone",
                    models.CharField(
                        blank=True, help_text="Recovery phone number", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_settings",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Settings",
                "verbose_name_plural": "Security Settings",
            },
        ),
    ]
