# syntax=docker/dockerfile:1

FROM python:3.11-slim AS base
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_NO_CACHE_DIR=off

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libmagic1 \
    && rm -rf /var/lib/apt/lists/*

# Requirements
COPY requirements/ ./requirements/
RUN python -m pip install --upgrade pip && \
    pip install -r requirements/dev.txt

# App source
COPY . .

# Create non-root user
RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE=destroyer.settings \
    DEBUG=1

# Default command: run Django dev server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

