# Generated by Django 5.2.5 on 2025-08-15 22:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Mark if this category contains sensitive data",
                    ),
                ),
                (
                    "default_retention_days",
                    models.IntegerField(
                        default=90, help_text="Default retention period in days"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "zip",
                                ]
                            )
                        ],
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the file", max_length=64
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("is_encrypted", models.BooleanField(default=False)),
                (
                    "encryption_method",
                    models.CharField(
                        choices=[
                            ("none", "No encryption"),
                            ("aes256", "AES-256"),
                            ("rsa", "RSA"),
                            ("pgp", "PGP"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "encryption_key_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to encryption key",
                        max_length=255,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("password_protected", models.BooleanField(default=False)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("scheduled_delete", "Scheduled for deletion"),
                            ("deleted", "Deleted"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "retention_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when document should be deleted",
                        null=True,
                    ),
                ),
                (
                    "deletion_date",
                    models.DateTimeField(
                        blank=True, help_text="Actual deletion date", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tags"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                            ("unshare", "Unshare"),
                            ("encrypt", "Encrypt"),
                            ("decrypt", "Decrypt"),
                        ],
                        max_length=50,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=255)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Access Log",
                "verbose_name_plural": "Document Access Logs",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "user"],
                        name="documents_d_documen_9a9fe5_idx",
                    ),
                    models.Index(
                        fields=["accessed_at"], name="documents_d_accesse_4721b9_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["owner", "status"], name="documents_d_owner_i_683479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["retention_date"], name="documents_d_retenti_17f553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_hash"], name="documents_d_file_ha_a7f76e_idx"
            ),
        ),
    ]
