# Generated by Django 5.2.5 on 2025-08-19 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Description of what this rule detects"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("regex", "Regular Expression"),
                            ("keyword", "Keyword Matching"),
                            ("ml_model", "Machine Learning Model"),
                            ("context", "Context-based"),
                            ("composite", "Composite Rule"),
                        ],
                        default="regex",
                        max_length=20,
                    ),
                ),
                (
                    "pattern",
                    models.TextField(help_text="Pattern, keywords, or model configuration"),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.8, help_text="Minimum confidence required for classification"
                    ),
                ),
                (
                    "target_classification",
                    models.CharField(
                        choices=[
                            ("pii", "Personally Identifiable Information"),
                            ("phi", "Protected Health Information"),
                            ("financial", "Financial Information"),
                            ("ip", "Intellectual Property"),
                            ("confidential", "Confidential Business Data"),
                            ("public", "Public Information"),
                            ("internal", "Internal Use Only"),
                            ("restricted", "Restricted Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low Sensitivity"),
                            ("medium", "Medium Sensitivity"),
                            ("high", "High Sensitivity"),
                            ("critical", "Critical Sensitivity"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Rule priority (lower numbers = higher priority)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("true_positives", models.IntegerField(default=0)),
                ("false_positives", models.IntegerField(default=0)),
                ("false_negatives", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="DataAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the data asset", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the data asset"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "primary_classification",
                    models.CharField(
                        choices=[
                            ("pii", "Personally Identifiable Information"),
                            ("phi", "Protected Health Information"),
                            ("financial", "Financial Information"),
                            ("ip", "Intellectual Property"),
                            ("confidential", "Confidential Business Data"),
                            ("public", "Public Information"),
                            ("internal", "Internal Use Only"),
                            ("restricted", "Restricted Access"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "secondary_classifications",
                    models.JSONField(
                        default=list, help_text="Additional classification categories"
                    ),
                ),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Sensitivity"),
                            ("medium", "Medium Sensitivity"),
                            ("high", "High Sensitivity"),
                            ("critical", "Critical Sensitivity"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_scanned", models.DateTimeField(auto_now=True)),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Size in bytes if applicable", null=True
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="File system path if applicable", max_length=1000
                    ),
                ),
                (
                    "database_table",
                    models.CharField(
                        blank=True, help_text="Database table if applicable", max_length=255
                    ),
                ),
                (
                    "retention_policy",
                    models.CharField(
                        blank=True, help_text="Applicable retention policy", max_length=255
                    ),
                ),
                (
                    "compliance_tags",
                    models.JSONField(
                        default=list, help_text="Compliance framework tags (GDPR, HIPAA, etc.)"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(blank=True, help_text="Required access level", max_length=50),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional custom metadata"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this asset is currently active"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "discovered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataLineage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("copy", "Direct Copy"),
                            ("transform", "Transformation"),
                            ("aggregate", "Aggregation"),
                            ("join", "Data Join"),
                            ("filter", "Filtered View"),
                            ("derive", "Derived Data"),
                            ("reference", "Reference Link"),
                        ],
                        default="copy",
                        max_length=20,
                    ),
                ),
                (
                    "transformation_logic",
                    models.TextField(
                        blank=True, help_text="Description of how data is transformed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_verified", models.DateTimeField(auto_now=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=1.0, help_text="Confidence in this lineage relationship (0.0-1.0)"
                    ),
                ),
                (
                    "impact_score",
                    models.FloatField(
                        default=0.5, help_text="Impact score if source changes (0.0-1.0)"
                    ),
                ),
                (
                    "source_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downstream_lineages",
                        to="discovery.dataasset",
                    ),
                ),
                (
                    "target_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_lineages",
                        to="discovery.dataasset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscoveryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_scan", "Full System Scan"),
                            ("incremental", "Incremental Scan"),
                            ("targeted", "Targeted Scan"),
                            ("scheduled", "Scheduled Scan"),
                            ("real_time", "Real-time Monitoring"),
                        ],
                        default="full_scan",
                        max_length=20,
                    ),
                ),
                (
                    "target_apps",
                    models.JSONField(
                        default=list, help_text="Django apps to scan (empty = all apps)"
                    ),
                ),
                (
                    "target_models",
                    models.JSONField(
                        default=list, help_text="Specific models to scan (empty = all models)"
                    ),
                ),
                (
                    "target_paths",
                    models.JSONField(default=list, help_text="File system paths to scan"),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True, help_text="Cron expression for scheduled jobs", max_length=100
                    ),
                ),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assets_discovered", models.IntegerField(default=0)),
                ("assets_classified", models.IntegerField(default=0)),
                ("errors_encountered", models.IntegerField(default=0)),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, help_text="Job-specific configuration parameters"
                    ),
                ),
                (
                    "results_summary",
                    models.JSONField(default=dict, help_text="Summary of job results"),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, help_text="Error messages and debugging info"),
                ),
                (
                    "classification_rules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Rules to apply during discovery",
                        to="discovery.classificationrule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataDiscoveryInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("classification", "Classification Pattern"),
                            ("compliance", "Compliance Issue"),
                            ("security", "Security Risk"),
                            ("governance", "Governance Recommendation"),
                            ("performance", "Performance Insight"),
                            ("quality", "Data Quality Issue"),
                        ],
                        default="classification",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "insight_data",
                    models.JSONField(
                        default=dict, help_text="Structured data supporting the insight"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, help_text="Actionable recommendations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("related_assets", models.ManyToManyField(blank=True, to="discovery.dataasset")),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("related_jobs", models.ManyToManyField(blank=True, to="discovery.discoveryjob")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "predicted_classification",
                    models.CharField(
                        choices=[
                            ("pii", "Personally Identifiable Information"),
                            ("phi", "Protected Health Information"),
                            ("financial", "Financial Information"),
                            ("ip", "Intellectual Property"),
                            ("confidential", "Confidential Business Data"),
                            ("public", "Public Information"),
                            ("internal", "Internal Use Only"),
                            ("restricted", "Restricted Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "predicted_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low Sensitivity"),
                            ("medium", "Medium Sensitivity"),
                            ("high", "High Sensitivity"),
                            ("critical", "Critical Sensitivity"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Confidence in this classification (0.0-1.0)"),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Confidence (< 60%)"),
                            ("medium", "Medium Confidence (60-80%)"),
                            ("high", "High Confidence (80-95%)"),
                            ("very_high", "Very High Confidence (> 95%)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "matched_patterns",
                    models.JSONField(default=list, help_text="Specific patterns that matched"),
                ),
                (
                    "context_information",
                    models.JSONField(
                        default=dict, help_text="Additional context used in classification"
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, help_text="Human validation of correctness", null=True
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_classifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classification_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_results",
                        to="discovery.classificationrule",
                    ),
                ),
                (
                    "data_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_results",
                        to="discovery.dataasset",
                    ),
                ),
                (
                    "discovery_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_results",
                        to="discovery.discoveryjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealTimeMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "monitor_type",
                    models.CharField(
                        choices=[
                            ("filesystem", "File System Changes"),
                            ("database", "Database Changes"),
                            ("api", "API Traffic"),
                            ("upload", "File Uploads"),
                            ("model_changes", "Model Instance Changes"),
                        ],
                        default="model_changes",
                        max_length=20,
                    ),
                ),
                (
                    "target_specification",
                    models.JSONField(default=dict, help_text="Configuration for what to monitor"),
                ),
                ("auto_classify", models.BooleanField(default=True)),
                ("alert_on_sensitive", models.BooleanField(default=True)),
                (
                    "alert_threshold",
                    models.CharField(
                        choices=[
                            ("low", "Low Sensitivity"),
                            ("medium", "Medium Sensitivity"),
                            ("high", "High Sensitivity"),
                            ("critical", "Critical Sensitivity"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("notification_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("items_monitored", models.IntegerField(default=0)),
                ("alerts_generated", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                (
                    "classification_rules",
                    models.ManyToManyField(blank=True, to="discovery.classificationrule"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_time_monitors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="monitoring_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("event_data", models.JSONField(default=dict)),
                ("was_classified", models.BooleanField(default=False)),
                ("triggered_alert", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_events",
                        to="discovery.dataasset",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_events",
                        to="discovery.realtimemonitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="classificationrule",
            index=models.Index(fields=["rule_type"], name="discovery_c_rule_ty_4bd479_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationrule",
            index=models.Index(
                fields=["target_classification"], name="discovery_c_target__7399da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationrule",
            index=models.Index(
                fields=["is_active", "priority"], name="discovery_c_is_acti_12df3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataasset",
            index=models.Index(
                fields=["primary_classification"], name="discovery_d_primary_21ee32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataasset",
            index=models.Index(fields=["sensitivity_level"], name="discovery_d_sensiti_389a0e_idx"),
        ),
        migrations.AddIndex(
            model_name="dataasset",
            index=models.Index(fields=["discovered_at"], name="discovery_d_discove_c90e44_idx"),
        ),
        migrations.AddIndex(
            model_name="dataasset",
            index=models.Index(fields=["last_scanned"], name="discovery_d_last_sc_a74534_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dataasset",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="datalineage",
            index=models.Index(fields=["relationship_type"], name="discovery_d_relatio_7fb71d_idx"),
        ),
        migrations.AddIndex(
            model_name="datalineage",
            index=models.Index(fields=["confidence_score"], name="discovery_d_confide_7f9094_idx"),
        ),
        migrations.AddIndex(
            model_name="datalineage",
            index=models.Index(fields=["created_at"], name="discovery_d_created_1bde85_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="datalineage",
            unique_together={("source_asset", "target_asset")},
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(fields=["status"], name="discovery_d_status_f47121_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(fields=["job_type"], name="discovery_d_job_typ_4c164f_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(fields=["created_at"], name="discovery_d_created_160e19_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(fields=["is_scheduled"], name="discovery_d_is_sche_c70551_idx"),
        ),
        migrations.AddIndex(
            model_name="datadiscoveryinsight",
            index=models.Index(fields=["insight_type"], name="discovery_d_insight_1f1d6e_idx"),
        ),
        migrations.AddIndex(
            model_name="datadiscoveryinsight",
            index=models.Index(fields=["severity"], name="discovery_d_severit_43f0f0_idx"),
        ),
        migrations.AddIndex(
            model_name="datadiscoveryinsight",
            index=models.Index(fields=["is_resolved"], name="discovery_d_is_reso_098524_idx"),
        ),
        migrations.AddIndex(
            model_name="datadiscoveryinsight",
            index=models.Index(fields=["created_at"], name="discovery_d_created_7efc2c_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationresult",
            index=models.Index(
                fields=["predicted_classification"], name="discovery_c_predict_11a6da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationresult",
            index=models.Index(fields=["confidence_score"], name="discovery_c_confide_bfba35_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationresult",
            index=models.Index(fields=["is_validated"], name="discovery_c_is_vali_f14c99_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationresult",
            index=models.Index(fields=["created_at"], name="discovery_c_created_dae9a3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="classificationresult",
            unique_together={("data_asset", "classification_rule")},
        ),
        migrations.AddIndex(
            model_name="realtimemonitor",
            index=models.Index(fields=["monitor_type"], name="discovery_r_monitor_d7891a_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimemonitor",
            index=models.Index(fields=["is_active"], name="discovery_r_is_acti_32951b_idx"),
        ),
        migrations.AddIndex(
            model_name="realtimemonitor",
            index=models.Index(fields=["created_at"], name="discovery_r_created_7cbfea_idx"),
        ),
        migrations.AddIndex(
            model_name="monitoringevent",
            index=models.Index(fields=["event_type"], name="discovery_m_event_t_eca90d_idx"),
        ),
        migrations.AddIndex(
            model_name="monitoringevent",
            index=models.Index(fields=["created_at"], name="discovery_m_created_0c058c_idx"),
        ),
        migrations.AddIndex(
            model_name="monitoringevent",
            index=models.Index(fields=["triggered_alert"], name="discovery_m_trigger_b38f97_idx"),
        ),
    ]
