# Generated by Django 5.2.8 on 2025-11-08 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Descriptive name for the model", max_length=100),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("spacy_ner", "spaCy NER"),
                            ("transformer", "Transformer Model"),
                            ("sklearn", "Scikit-learn Classifier"),
                            ("hybrid", "Hybrid Model"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "classification_types",
                    models.JSONField(
                        default=list,
                        help_text="Classification types this model handles (PII, PHI, etc.)",
                    ),
                ),
                ("model_path", models.CharField(help_text="Path to model files", max_length=500)),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Model configuration parameters"),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, help_text="Overall accuracy (0-1)", null=True),
                ),
                (
                    "precision",
                    models.FloatField(blank=True, help_text="Precision score (0-1)", null=True),
                ),
                (
                    "recall",
                    models.FloatField(blank=True, help_text="Recall score (0-1)", null=True),
                ),
                ("f1_score", models.FloatField(blank=True, help_text="F1 score (0-1)", null=True)),
                (
                    "version",
                    models.CharField(help_text="Model version (e.g., 1.0.0)", max_length=20),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="Model is active and can be used"),
                ),
                (
                    "is_production",
                    models.BooleanField(default=False, help_text="Model is deployed in production"),
                ),
                (
                    "training_samples",
                    models.IntegerField(default=0, help_text="Number of samples used for training"),
                ),
                (
                    "training_duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Time taken to train the model", null=True
                    ),
                ),
                (
                    "training_params",
                    models.JSONField(
                        default=dict, help_text="Hyperparameters used during training"
                    ),
                ),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ml_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent model if this is a fine-tuned version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_models",
                        to="discovery.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="MLClassificationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entities",
                    models.JSONField(default=list, help_text="Detailed entity extraction results"),
                ),
                (
                    "regex_matches",
                    models.JSONField(default=list, help_text="Entities found by regex patterns"),
                ),
                (
                    "ml_matches",
                    models.JSONField(default=list, help_text="Entities found by ML model"),
                ),
                (
                    "regex_confidence",
                    models.FloatField(help_text="Confidence score from regex patterns (0-1)"),
                ),
                (
                    "ml_confidence",
                    models.FloatField(help_text="Confidence score from ML model (0-1)"),
                ),
                (
                    "combined_confidence",
                    models.FloatField(help_text="Final combined confidence score (0-1)"),
                ),
                (
                    "processing_time_ms",
                    models.FloatField(help_text="Time taken to process (milliseconds)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classification_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_result",
                        to="discovery.classificationresult",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classification_results",
                        to="discovery.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("sample_size", models.IntegerField(help_text="Number of samples evaluated")),
                ("true_positives", models.IntegerField(default=0)),
                ("false_positives", models.IntegerField(default=0)),
                ("true_negatives", models.IntegerField(default=0)),
                ("false_negatives", models.IntegerField(default=0)),
                (
                    "class_metrics",
                    models.JSONField(
                        default=dict, help_text="Metrics broken down by classification type"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="discovery.mlmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("training_samples", models.IntegerField(help_text="Number of training samples")),
                (
                    "validation_samples",
                    models.IntegerField(help_text="Number of validation samples"),
                ),
                ("test_samples", models.IntegerField(help_text="Number of test samples")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("epochs", models.IntegerField(default=10, help_text="Number of training epochs")),
                ("batch_size", models.IntegerField(default=8, help_text="Training batch size")),
                ("learning_rate", models.FloatField(default=0.001, help_text="Learning rate")),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, help_text="Additional hyperparameters"),
                ),
                ("train_accuracy", models.FloatField(blank=True, null=True)),
                ("val_accuracy", models.FloatField(blank=True, null=True)),
                ("test_accuracy", models.FloatField(blank=True, null=True)),
                ("train_loss", models.FloatField(blank=True, null=True)),
                ("val_loss", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("logs", models.TextField(blank=True, help_text="Training logs")),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_batches",
                        to="discovery.mlmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Training batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_correct", models.BooleanField(help_text="Was the classification correct?")),
                (
                    "corrected_type",
                    models.CharField(
                        blank=True,
                        help_text="Corrected classification type if wrong",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "corrected_entities",
                    models.JSONField(
                        blank=True, help_text="Corrected entity annotations", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes or explanation"),
                ),
                (
                    "incorporated_in_training",
                    models.BooleanField(
                        default=False, help_text="Feedback has been incorporated into training data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When feedback was incorporated", null=True
                    ),
                ),
                (
                    "classification_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="discovery.classificationresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Training batch where this feedback was used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_used",
                        to="discovery.trainingbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField(help_text="Raw text to classify")),
                (
                    "entities",
                    models.JSONField(
                        default=list,
                        help_text='Entity annotations: [{"start": 0, "end": 5, "label": "PII"}]',
                    ),
                ),
                (
                    "classification_type",
                    models.CharField(
                        help_text="Primary classification type (PII, PHI, etc.)", max_length=50
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user_feedback", "User Feedback"),
                            ("manual", "Manual Annotation"),
                            ("imported", "Imported Dataset"),
                            ("synthetic", "Synthetic Data"),
                        ],
                        help_text="Source of this training example",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="Language code (ISO 639-1)", max_length=10
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, help_text="Has been manually verified"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "used_in_training",
                    models.BooleanField(
                        default=False, help_text="Has been used in at least one training run"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this example was used in training",
                        null=True,
                    ),
                ),
                (
                    "times_used",
                    models.IntegerField(default=0, help_text="Number of times used in training"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_training_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(fields=["model_type"], name="discovery_m_model_t_7c7ad6_idx"),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["is_active", "is_production"], name="discovery_m_is_acti_af7788_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(fields=["-trained_at"], name="discovery_m_trained_779841_idx"),
        ),
        migrations.AddIndex(
            model_name="mlclassificationresult",
            index=models.Index(fields=["model"], name="discovery_m_model_i_a8abdc_idx"),
        ),
        migrations.AddIndex(
            model_name="mlclassificationresult",
            index=models.Index(fields=["-created_at"], name="discovery_m_created_af440d_idx"),
        ),
        migrations.AddIndex(
            model_name="modelmetric",
            index=models.Index(
                fields=["model", "-recorded_at"], name="discovery_m_model_i_7e6b8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingbatch",
            index=models.Index(fields=["status"], name="discovery_t_status_b0cca9_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingbatch",
            index=models.Index(fields=["-created_at"], name="discovery_t_created_026d14_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationfeedback",
            index=models.Index(fields=["is_correct"], name="discovery_c_is_corr_b6a136_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationfeedback",
            index=models.Index(
                fields=["incorporated_in_training"], name="discovery_c_incorpo_8a332b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationfeedback",
            index=models.Index(fields=["-created_at"], name="discovery_c_created_d031cf_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingdataset",
            index=models.Index(
                fields=["classification_type"], name="discovery_t_classif_a3b5c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingdataset",
            index=models.Index(fields=["source"], name="discovery_t_source_4b0e3c_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingdataset",
            index=models.Index(fields=["verified"], name="discovery_t_verifie_a7b324_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingdataset",
            index=models.Index(fields=["language"], name="discovery_t_languag_a347f8_idx"),
        ),
    ]
